// Would You Rather decks (light and dark squares).

const wouldYouRatherQuestions = [
  "Have a pet dinosaur the size of a dog or a dog the size of a dinosaur?",
  "Be able to fly, but only 1 meter off the ground, or be invisible, but only when you close your eyes?",
  "Eat pizza every day or a burger every day?",
  "Only be able to play Mario Bros your whole life or Sonic?",
  "Have to blink one eye at a time or always hop on one foot to walk?",
  "Have to do everything at a run or do everything in slow motion?",
  "Have a camel as your only means of transportation or an ostrich?",
  "Have the power to make food appear out of nowhere or have your dirty laundry wash itself?",
  "Have your voice crack in the middle of a scream or sneeze and have snot fly out?",
  "Shoot webs like Spider-Man or have claws like Wolverine?",
  "Only be able to drink hot liquids in summer or ice-cold liquids in winter?",
  "Have every floor you step on turn into a trampoline or a slide?",
  "Have your hands glued together or your feet tied together?",
  "Sweat honey or cry milk?",
  "Have x-ray vision (that doesn't turn off) or super hearing (that you can't turn down)?",
  "Be allergic to your favorite food or have to eat it for every meal?",
  "Never be able to use a pillow again or have to use a rock as a pillow?",
  "Host the Oscars and trip on stage or forget the lyrics while singing at the Super Bowl?",
  "Age physically from the neck up or from the neck down?",
  "Have a phone battery that never goes above 10% or internet that drops every 15 minutes?",
  "Live on a desert island full of monkeys or in a forest full of friendly wolves?",
  "Shapeshift or be able to stop time for 1 minute a day?",
  "Marry your favorite actor/actress but they are unbearable, or an amazing anonymous person?",
  "Travel the world backpacking but with no money, or stay home for the rest of your life in a mansion?",
  "Cry watching a margarine commercial or laugh at a joke you didn't understand?",
  "Pet a shark or hug a porcupine?",
  "Have the ability to heal minor wounds or fix any broken object?",
  "Only be able to use social media from 2010 (Myspace, MSN) or not be able to use any?",
  "Lose your sense of taste or your sense of smell?",
  "Work your dream job for minimum wage or the worst job in the world and become a millionaire?",
  "Say the wrong name during intimacy or forget your own phone number when giving it to a crush?",
  "Control fire or control water?",
  "Never eat cheese again or never eat bread again?",
  "Wake up tomorrow in a Lego body or a Play-Doh body?",
  "Have a laugh that sounds like a pig snorting or like a car horn?",
  "Never be able to wash your hair again or never brush your teeth again?",
  "Let out a loud fart in a crowded elevator or in a silent classroom?",
  "Have all the insects in the world be the size of cats or have all cats be venomous?",
  "Be able to teleport (but always arrive naked) or fly (but at 5 km/h)?",
  "Have chairs always break when you sit on them or have doors always locked on the first try?",
  "Play video games all day but always lose, or play only 10 minutes but always win?",
  "Feel no physical pain at all or be completely tickle-proof?",
  "Not be able to use emojis in messages or only be able to reply with emojis?",
  "Bark every time you laugh or meow every time you yawn?",
  "Cry mayonnaise or spit soap?",
  "Have the voice of Mickey Mouse or Darth Vader?",
  "Have to drink a liter of soda for breakfast or seawater for dinner?",
  "Cry colored tears or sweat glitter?",
  "Wake up every day at 4 AM or only be able to go to sleep after 3 AM?",
  "Be able to ride a lion or fly on the back of an eagle?",
  "Only be able to eat with chopsticks or only with your hands?",
  "Only be able to walk backwards or only be able to run instead of walking?",
  "Have fingers that shoot lasers or legs that run at the speed of light?",
  "Be a stray cat or a pampered dog?",
  "Have super strength only in your legs or only in your arms?",
  "Have to put ketchup on everything or mayonnaise on everything?",
  "Have to yell \"Oops!\" every time you sit down or clap every time you stand up?",
  "Be the villain in a Disney movie or the extra who dies in an action movie?",
  "Have no eyebrows or have no nails?",
  "Never use a smartphone again or never use a computer again?",
  "Walk around with a rip in the back of your pants all day or with toilet paper stuck to your shoe?",
  "Fight 1 duck-sized bear or 100 bear-sized ducks?",
  "Read minds (but not be able to turn it off) or see the future (but only 10 seconds ahead)?",
  "Live at the bottom of the ocean or in outer space?",
  "Time travel to the past (without being able to change anything) or to the future (without being able to return)?",
  "Drink salty coffee or spicy juice?",
  "Be bald forever or have your whole body covered in hair that grows really fast?",
  "Take cold showers for the rest of your life or only be able to shower once a week?",
  "Be able to talk to animals or speak all the languages in the world?",
  "Never eat sweets again or never eat fried food again?",
  "Have all your clothes made of canvas or bubble wrap?",
  "Live without Netflix/streaming or live without Spotify/music?",
  "Burp loudly at a funeral or laugh uncontrollably during a wedding?",
  "Eat a whole lemon (with the peel) or a whole raw onion?",
  "Be chased by an angry goose for the rest of your life or by a raincloud that only rains on you?",
  "Have your hair change color according to your mood or your nose grow when you lie (like Pinocchio)?",
  "Have your phone's search history read aloud to your family or to your coworkers?",
  "Have your food always be too spicy or too bland?",
  "Fight one giant baby or a hundred miniature versions of yourself?",
  "Go on a reality show and be hated by the public or be the first eliminated that no one remembers?",
  "Have really short arms (like a T-Rex) or really short legs?",
  "Always be 10 minutes late or always be 20 minutes early for everything?",
  "Accidentally call your boss \"mom/dad\" or send a screenshot of a conversation to the person you were talking about?",
  "Have your pants fall down in the middle of the street or have your shirt inside out all day without noticing?",
  "Breathe underwater or never need to sleep again?",
  "Have to narrate your own life like a sports commentator or a National Geographic documentary?",
  "Have wooden teeth or rubber fingers?",
  "Always have a pebble in your shoe or have an itchy shirt tag?",
  "Have food stuck in your teeth for an entire first date or have bad breath?",
  "Swap bodies with your pet for a day or with an ant for a week?",
  "Be famous for something embarrassing or never be recognized for a great invention of yours?",
  "Wear winter clothes in summer or summer clothes in winter?",
  "Have your shoes make a squeaky duck sound with every step or have clothes that flash?",
  "Only be able to listen to the same song for the rest of your life or watch the same movie every day?",
  "Forget the name of someone important in the middle of a presentation or trip and fall on stage?",
  "Have bat wings or a monkey tail?",
  "Live in The Walking Dead universe or The Hunger Games universe?",
  "Have an eye in the middle of your forehead or two noses?",
  "Send a voice memo of you singing in the shower to the work group chat or a picture making a funny face?",
  "Be a wizard in the Harry Potter world or a Jedi in Star Wars?",
  "Eat stale popcorn or flavorless chips?",
  "Live in a romantic comedy full of clichés or a horror movie where you are the survivor?",
  "Speak entirely in rhymes or by singing?",
  "Wave back at someone who wasn't waving at you or reply to someone who was wearing earphones?",
  "Have a pig snout or elephant ears?",
  "Have the power to make anyone laugh or make anyone fall asleep?",
  "Have to start every sentence with \"Back in my day...\" or end every sentence with \"And that's that\"?",
  "Replace Batman (and fight crime with no superpowers) or Aquaman (and live in the water)?",
  "Eat a birthday cake for lunch or lasagna for breakfast?",
  "Have legs that dance on their own when music plays or arms that hug everyone you see?",
  "Have an infinite fountain of ice cream or french fries?",
  "Have a dwarf following you playing the trombone all day or a mime copying your movements?",
  "Be reborn as a seagull or as an urban pigeon?",
  "Be an anime character or a Cartoon Network character?",
  "Have all chocolate taste like broccoli or all broccoli taste like chocolate?",
  "Get a face tattoo chosen by your best friend or a back tattoo chosen by your mom?",
  "Be 3 meters (10 feet) tall or 50 centimeters (20 inches) tall?",
  "Only be able to wear yellow clothes or brown clothes?",
  "Sleep hanging upside down (like a bat) or standing up (like a horse)?",
  "Find out your whole life was a \"Truman Show\" style program or that we are living in the \"Matrix\"?",
  "Never need to sleep again or never need to use the bathroom again?",
  "Speak with a really high-pitched voice when nervous or stutter uncontrollably?",
  "Accidentally greet someone with a kiss on the lips or try to give a handshake and be left hanging?",
  "Have to lick all doorknobs before opening the door or spin around before entering a place?",
  "Have to wear clown clothes every day or wear swimwear in winter?",
  "Mix beans into your ice cream or put dulce de leche on your rice?",
  "Get stuck in an elevator with Ronald McDonald or the Michelin Man?"
];

const darkWouldYouRatherQuestions = [
  "Have to amputate your own finger without anesthesia to save a stranger's life, or let the stranger die to keep your body intact?",
  "Discover a terrifying secret about your parents that changes how you see them, or a secret about yourself that your mind had blocked out?",
  "Upload your mind and consciousness into an immortal computer (discarding your flesh body), or die naturally at 80 and fade from the universe?",
  "Lose your dominant arm in a shark attack, or lose both legs in a car accident?",
  "Marry someone you love madly who doesn't love you with the same intensity, or marry someone who idolizes you but for whom you feel no passion?",
  "Press a button that gives you $5 million now but instantly kills a random stranger, or not press it and continue your normal life struggling with bills?",
  "Remember absolutely everything that ever happened to you (including all physical pain, grief, and humiliation with perfect clarity), or forget something new every day?",
  "Be trapped on a desert island completely alone for 5 years, or trapped in a bunker with the person you hate most in the world for 1 year?",
  "Win the lottery but be forbidden to tell anyone (even family), or earn a great salary while being absurdly famous with no privacy?",
  "Find out your partner cheated in the past but have a guarantee they never will again, or live with constant suspicion without ever having proof?",
  "Live the rest of your life without tasting anything, or without seeing any colors (everything in black and white)?",
  "Know exactly the day you will go bankrupt, or know nothing and live in constant anxiety of losing everything?",
  "Know exactly *how* your current relationship will end, or *when* it will end?",
  "Find out you only have 24 hours of healthy life left, or have to choose the exact day of your unchangeable death 50 years from now?",
  "Receive $10 million to never work again but never be able to travel, or have to work until you're 80 but travel the world for free?",
  "Have your partner read all your thoughts, or have them get free access to all your deleted messages?",
  "Personally assassinate a genocidal dictator in their crib (via time travel) to prevent a world war, or keep your soul intact, don't spill blood, and let millions die in the war?",
  "Find your absolute soulmate but have to live on different continents, or marry a merely tolerable neighbor forever?",
  "Discover you are an android whose childhood memories were fabricated by a programmer, or discover you are the last real human living among perfect robots?",
  "Have extremely controlling parents who fund a life of luxury for you, or liberal and absent parents who give you neither a cent nor affection?",
  "Have a predictive system state with 99% accuracy you will commit a murder and arrest you beforehand, or predict you'll be a victim, leaving you in chronic paranoia?",
  "Wake up tomorrow knowing 10 years have passed and you have no memory of what you did, or have to live the next 10 years in solitary confinement?",
  "Have to fight to the death against your biggest idol in an arena, or against an AI robot programmed to have no mercy?",
  "Save a burning archive containing humanity's greatest lost artworks and disease cures, or save an elderly janitor trapped in the same room?",
  "Be the only person in the world who knows the truth about a global scandal but no one believes you, or naively believe the lie along with the masses?",
  "Be judged in a criminal court by a ruthless, impartial, and merciless AI, or by a corrupt, tired, and prejudiced human judge?",
  "Instantly know the worst thing people think about you upon first meeting, or never know if anyone actually likes you or is just being polite?",
  "Be buried alive in a tight coffin for 2 hours (with a guarantee you'll be pulled out), or skydive from a crashing plane?",
  "Date someone who gets along terribly with your whole family, or someone your best friends absolutely hate?",
  "Live the rest of your life in a perfect computer simulation made just for you, or live in the brutal, painful, cold reality outside the machine?",
  "Discover the cure for a disease but your rival takes all the credit, or take credit for a genius discovery you didn't make and become a millionaire?",
  "Pull the plug on the machine keeping your mother in an irreversible coma for 20 years (and live with the guilt), or be forced to pay crushing hospital bills that keep you in poverty until you die?",
  "Have a marriage with no physical intimacy, or a marriage with no deep conversations?",
  "Live in a world where the internet was permanently destroyed (back to the 80s), or in the epicenter of WWIII fought entirely in cyberspace (hacking hospitals, banks, etc.)?",
  "Develop prosopagnosia and no longer be able to recognize your mother's/partner's/children's faces, or lose the ability to recognize their voices?",
  "The cruel classic: Have to choose which of your parents lives in a rescue situation, or choose neither and let chance decide their deaths?",
  "Try to survive in an apocalyptic world full of slow, dumb zombies (but billions of them), or with ultra-fast, smart aliens (but fewer of them)?",
  "Keep the secret of a friend's severe betrayal, or tell their partner and ruin both of their lives?",
  "Have to fire your best friend to save your company, or keep their job and go bankrupt alongside them?",
  "Have the whole world receive terrifying, irrefutable proof of alien observers and enter collective collapse, or be the only one who knows and carry that madness and loneliness alone?",
  "Save your own life from multiple organ failure using organs from prisoners executed against their will specifically to cure you, or refuse and die ethically?",
  "Live with an uncontrollable, paralyzing phobia of water (hydrophobia), or an uncontrollable, paralyzing phobia of the dark?",
  "Have all your friends completely lose their memories of you, or have you forget the faces and names of all of them?",
  "Survive a terrifying plane crash as the only traumatized survivor, or have a phobia of never being able to enter an airborne or motorized vehicle again?",
  "Be the millionaire CEO of a company that actively destroys the environment, or a broke activist who fights it all your life without success?",
  "Have to be the dictator who chooses an entire demographic to disappear (e.g., everyone over 90) to solve Earth's resource collapse, or cross your arms and let the planet starve tomorrow?",
  "Magically erase your biggest past regret, completely changing who you are today, or keep living with that suffocating guilt eternally?",
  "Live with your invasive mother-in-law/father-in-law in the same house for life, or be forced to move to another country alone, leaving your partner behind for 5 years?",
  "Have the incredibly sharp hearing of a dog (where city noise is torture), or the vision of an eagle (but completely lose peripheral vision)?",
  "Have your entire social circle know exactly how much money is in your bank account, or have them read a document detailing all your bodily insecurities?",
  "Be the godparent to the child of the ex who hurt you, or not even be invited to your current best friend's wedding?",
  "Survive an attack by a swarm of 10,000 furious bees, or be swallowed whole by a giant snake (and be rescued alive later)?",
  "Suffer from retrograde amnesia every time you fall in love, or every time you achieve a major life goal?",
  "Have to defuse a time bomb by cutting a wire on a 50/50 guess, or pilot a crashing helicopter having never taken lessons?",
  "Accidentally send a nude photo to your parents, or purposefully send an audio file severely cursing out your boss by mistake?",
  "Choose your children's ideal career for them, or let them choose what they love and fail miserably?",
  "Spend the rest of your life trying to change the one you love, or accept that they will never change their worst flaws?",
  "Travel through deep space on a one-way exploration mission (knowing you'll die in the stars), or never be allowed to leave your hometown limits?",
  "Live in a luxurious underground bunker for life without ever seeing sunlight again, or in a semi-destroyed, dangerous, and radioactive surface world?",
  "Tell an elaborate lie that saves a life, or tell a brutal truth that destroys an entire family?",
  "Have a brilliant mentor who humiliates you to teach you, or have to learn everything yourself by making bitter mistakes?",
  "Know that you are your partner's second choice, or that they are with you only for financial convenience?",
  "Have everyone you love age and die twice as fast while you stay intact and outlive them, or age three times as fast so you don't have to watch them leave?",
  "Have your Google search history (even incognito) shown on a projector at your funeral, or all the photos from your phone's hidden gallery printed on a mural?",
  "Cut off your own hand with a dull handsaw, or an anesthetized stranger's hand to escape a \"Saw\" style trap?",
  "Never have to pay for food again in your life, or never have to pay for housing again?",
  "Lose the ability to feel jealousy forever, or the ability to miss someone?",
  "Save a family member's life but they lose their memory and hate you forever, or let them die while they tell you how much they love you?",
  "Have the painful gift of always knowing when someone is lying to you, or be able to lie perfectly without anyone ever finding out?",
  "Have your biggest, most shameful secret exposed on national TV, or have the biggest secrets of your three best friends exposed because of you?",
  "Have your dream job paying incredibly well but with an abusive boss, or a boring job paying less with the best boss in the world?",
  "Have a chip implanted in your optic nerve that records everything you see for a government database, or allow companies to beam ads into your mind while you sleep?",
  "Have paralyzing panic attacks every time you feel intense happiness, or feel a constant deep sadness but remain highly functional and productive?",
  "Donate your kidney to an ex-best friend who stopped talking to you years ago, or refuse and have them find out you said no?",
  "Never be able to give a kiss again, or never be able to give/receive a hug again?",
  "Divert a runaway train to intentionally run over an innocent child, or do nothing and let the train kill 5 loose heinous criminals?",
  "Only have time to save one from a burning house: your beloved pet of 10 years, or a human baby from a family you don't know?",
  "Wake up tomorrow in a psychiatric hospital diagnosed with schizophrenia and no one believes your sanity, or actually go insane and believe you own the world?",
  "Get rich by selling your company's vital secrets, or get promoted by being 100% honest but with a stagnant salary?",
  "Confess to a crime you didn't commit to save someone you love, or let that person go to jail unjustly?",
  "Lose all your money and assets tomorrow, or lose all your memories from the last 5 years?",
  "Constantly hear a voice in your head narrating your biggest insecurities, or hallucinate shadows under your bed that you know aren't real?",
  "Lend all your savings to a friend knowing they will never be able to pay you back, or refuse and ruin the friendship forever?",
  "Be hunted by an armed serial killer in a dark maze, or by a pack of starving wolves in a snowy forest?",
  "Know that all your friends have a parallel group chat without you where they talk about you, or that they defend you behind your back but are fake to your face?",
  "Have an exact clone of you doing all your hard work daily, knowing it developed feelings and hates being your slave, or do all the work yourself?",
  "Discover at 30 that you were switched at birth and your biological parents are billionaires who want you back, or stay with the humble family that raised you?",
  "Have the supernatural power to cure anyone's cancer with a touch, but the disease passes into your body for half the time they suffered, or give up the power?",
  "Surrender your biological and DNA data to an authoritarian government in exchange for immunity to disease, or risk dying of a treatable cancer to maintain your privacy?",
  "Trade 50% of your intelligence for paralyzing, magnetic beauty, or trade all your aesthetic beauty for an IQ of 200 (world-class genius)?",
  "Watch your best friend marry the person who destroyed your life, or the greatest love of your life whom you never got over?",
  "Have to say exactly what you think, with no filter, for 24 hours straight, or not be able to speak at all for 1 month?",
  "Cause the immediate bankruptcy of a small working-class town to guarantee immeasurable wealth for your family for generations, or donate all your wealth and live on the streets to save them?",
  "Be banned for life from using any post-2000 technology (smartphones, internet, streaming), or live permanently immersed in VR goggles, unable to return to the physical world?",
  "Discover your whole life and the people in it were a fabricated lie to observe you, or live the happy lie without ever discovering the truth?",
  "Be remembered in history as a terrible, unethical genius, or be completely forgotten as a wonderful person?",
  "Be responsible for releasing the world's last pair of pandas into the wild knowing they don't know how to survive and will be eaten, or keep them suffering in tiny cages so the species doesn't end?",
  "Be your parents' favorite child but have your siblings hate you with a passion, or be the \"black sheep\" but have your siblings' unconditional loyalty?",
  "Have absolute professional success but work 16 hours a day with no days off, or have a mediocre life working only 4 hours a day?",
  "Forget your first love completely, or never be able to forget them, ruining all your future relationships?",
  "Have to report your sibling to the police for an unbailable crime, or go to jail as an accomplice to help them cover it up?",
  "Be trapped in a time loop reliving the worst day of your life 100 times, or relive the best day of your life knowing you will permanently die the next day?",
  "Have the option (and social pressure) to genetically edit your unborn children to be intellectually perfect, or risk the natural course with potential severe diseases?",
  "Have to face your worst traumas every day in an extremely vivid 10-minute dream, or never be able to dream again and have heavy, empty sleep?",
  "Have to reveal and read your browsing history to the person you respect most, or be forced to read their private diary?",
  "Steal $1 million from a bank with absolute certainty you won't be caught, or earn $100,000 exhaustingly and honestly?",
  "Have to confess the worst thing you've ever done to the love of your life, or have them confess the worst thing they did to you?",
  "Get back together with your most toxic ex for a year in exchange for $1 million, or stay strictly single for 5 years?",
  "Lose all your current friends for a chance to meet the best people in the world tomorrow, or keep your friends but your relationships never evolve?",
  "Have exponential financial gains but need to move cities every 6 months, or have a fixed salary living in your dream house?",
  "End all hunger and poverty on Earth immediately, but the price is humanity loses all forms of art and music forever, or keep the world unjust and imperfect as it is?",
  "Discover your family has a history of rare, incurable genetic diseases, or inherit a massive debt tied to your name made by your grandfather?",
  "Go 30 days without drinking clean water (only forcibly filtered/boiled dirty water), or 30 days eating only live insects?",
  "Know how and when the world will end but be powerless to stop it, or not know and be caught by surprise while drinking coffee?",
  "Feel physical pain equivalent to a full-body thermal shock when you tell a lie, or when someone lies directly to you?",
  "Download instant skills into your mind (piano, martial arts) but each download costs 1 year of your life, or take 10 natural years of discipline to master something?",
  "Find out your partner is a wanted criminal but treats you like royalty, or that they are a model citizen but ignore you?",
  "Replace your real eyes with perfect bionic lenses with a corporate watermark blinking in your vision every 10 minutes, or become severely nearsighted and intolerant to glasses?",
  "Romantically date a perfectly tailored AI that lives in your devices to fulfill your needs, or date a real human full of flaws, traumas, and baggage?",
  "Discover you have a twin sibling who is a wanted criminal, or that you were adopted and your real parents were assassin spies?",
  "Date someone incredibly attractive with a terrible sense of humor, or someone completely unattractive who makes you laugh until you cry?",
  "Have your child be an absolute genius but clinically depressed, or have well below-average intelligence but be the happiest person on Earth?",
  "Be forced to share an apartment with someone who knows your worst secret, or with someone whose terrifying worst secret you know?",
  "Cut ties with your entire family in exchange for lifelong financial security, or refuse the money and live in misery, but together?",
  "Have full awareness that you are slowly developing dementia, or lose your mind overnight and not realize you are a burden to your family?",
  "Publicly defend a friend from being \"canceled,\" knowing they are wrong, and ruin your reputation, or abandon them to the wolves to save yourself?",
  "Genuinely forgive the person who murdered or destroyed something vital in your life to cleanse your soul, or seek revenge and destroy them, but lose all your own financial and social success in the process?",
  "Have the telepathic ability to hear only people's negative thoughts about your body, or hear when they are lying and feeling pity for you?",
  "Find a legendary mystic artifact (like the Holy Grail) but an international mafia hunts your family mercilessly for it, or rebury it and live a quiet life knowing you made history's greatest discovery in secret?",
  "Have the only app in the world that translates an incoming alien signal revealing they are aggressive and coming to kill us, or not have the app and wait for the apocalypse in ignorance?",
  "Make a lot of money but physically age twice as fast, or be eternally poor but have prolonged youth?",
  "Discover a severe betrayal through a friend, or catch them red-handed by pure accident?",
  "Have the power to discover anyone's worst fear just by looking at them, or have everyone instantly know your worst fear upon meeting you?"
];

function createLightQuestionDeck() {
  return [...wouldYouRatherQuestions];
}

function createDarkQuestionDeck() {
  return [...darkWouldYouRatherQuestions];
}

function shuffleList(list) {
  const copy = [...list];
  for (let i = copy.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

function drawLightQuestion() {
  if (!gameState.remainingLightQuestions?.length) {
    gameState.remainingLightQuestions = shuffleList(
      createLightQuestionDeck()
    );
  }

  if (gameState.testMode) {
    const list = gameState.remainingLightQuestions;
    return list[Math.floor(Math.random() * list.length)];
  }

  return gameState.remainingLightQuestions.pop();
}

function drawDarkQuestion() {
  if (!gameState.remainingDarkQuestions?.length) {
    gameState.remainingDarkQuestions = shuffleList(
      createDarkQuestionDeck()
    );
  }

  if (gameState.testMode) {
    const list = gameState.remainingDarkQuestions;
    return list[Math.floor(Math.random() * list.length)];
  }

  return gameState.remainingDarkQuestions.pop();
}
