const PICTIONARY_DB_MASTER = {
  1: {
    name: "[P] Pessoa/Animal",
    words: [
      "Cachorro",
      "Gato",
      "Leão",
      "Macaco",
      "Girafa",
      "Elefante",
      "Urso",
      "Pinguim",
      "Canguru",
      "Coelho",
      "Tubarão",
      "Baleia",
      "Tigre",
      "Águia",
      "Sapo",
      "Cobra",
      "Cavalo",
      "Vaca",
      "Galinha",
      "Porco",
      "Policial",
      "Bombeiro",
      "Médico",
      "Professor",
      "Astronauta",
      "Palhaço",
      "Mágico",
      "Pirata",
      "Ninja",
      "Zumbi",
      "Vampiro",
      "Fantasma",
      "Bruxa",
      "Rei",
      "Rainha",
      "Princesa",
      "Presidente",
      "Cantor",
      "Ator",
      "Jogador de futebol",
      "Dançarino",
      "Pintor",
      "Cozinheiro",
      "Marceneiro",
      "Pescador",
      "Bebê",
      "Idoso",
      "Gêmeos",
      "Sereia",
      "Centauro",
    ],
  },
  2: {
    name: "[O] Objeto",
    words: [
      "Megafone",
      "Cadeira",
      "Mesa",
      "Computador",
      "Celular",
      "Televisão",
      "Geladeira",
      "Fogão",
      "Cama",
      "Travesseiro",
      "Espelho",
      "Relógio",
      "Óculos",
      "Chapéu",
      "Sapato",
      "Camiseta",
      "Calça",
      "Meia",
      "Mochila",
      "Bolsa",
      "Guarda-chuva",
      "Faca",
      "Garfo",
      "Colher",
      "Prato",
      "Copo",
      "Garrafa",
      "Panela",
      "Vassoura",
      "Balde",
      "Lixo",
      "Lápis",
      "Caneta",
      "Caderno",
      "Livro",
      "Tesoura",
      "Cola",
      "Fita adesiva",
      "Grampeador",
      "Bola",
      "Boneca",
      "Carrinho",
      "Pipa",
      "Bicicleta",
      "Skate",
      "Patins",
      "Violão",
      "Piano",
      "Bateria",
      "Microfone",
    ],
  },
  3: {
    name: "[A] Ação",
    words: [
      "Correr",
      "Andar",
      "Pular",
      "Nadar",
      "Voar",
      "Escalar",
      "Rastejar",
      "Dançar",
      "Cantar",
      "Gritar",
      "Sussurrar",
      "Chorar",
      "Rir",
      "Sorrir",
      "Tossir",
      "Espirrar",
      "Bocejar",
      "Dormir",
      "Acordar",
      "Comer",
      "Beber",
      "Mastigar",
      "Engolir",
      "Cozinhar",
      "Limpar",
      "Lavar",
      "Secar",
      "Passar roupa",
      "Varrer",
      "Esfregar",
      "Pintar",
      "Desenhar",
      "Escrever",
      "Ler",
      "Digitar",
      "Assistir",
      "Ouvir",
      "Falar",
      "Pensar",
      "Sonhar",
      "Lutar",
      "Socar",
      "Chutar",
      "Defender",
      "Esquivar",
      "Abraçar",
      "Beijar",
      "Cumprimentar",
      "Despedir",
      "Acenar",
    ],
  },
  4: {
    name: "[D] Difícil",
    words: [
      "Visão",
      "Saudade",
      "Gravidade",
      "Fofoca",
      "Ironia",
      "Sarcasmo",
      "Amor",
      "Ódio",
      "Tristeza",
      "Alegria",
      "Medo",
      "Coragem",
      "Esperança",
      "Desespero",
      "Confiança",
      "Dúvida",
      "Mentira",
      "Verdade",
      "Segredo",
      "Mistério",
      "Magia",
      "Ilusão",
      "Sonho",
      "Pesadelo",
      "Tempo",
      "Espaço",
      "Passado",
      "Presente",
      "Futuro",
      "Infinito",
      "Nada",
      "Tudo",
      "Paz",
      "Guerra",
      "Caos",
      "Ordem",
      "Justiça",
      "Injustiça",
      "Liberdade",
      "Prisão",
      "Sucesso",
      "Fracasso",
      "Sorte",
      "Azar",
      "Destino",
      "Coincidência",
      "Karma",
      "Paradoxo",
      "Déjà vu",
      "Empatia",
    ],
  },
  5: {
    name: "[L] Lugar",
    words: [
      "Praia",
      "Montanha",
      "Floresta",
      "Deserto",
      "Ilha",
      "Caverna",
      "Cachoeira",
      "Rio",
      "Lago",
      "Mar",
      "Cidade",
      "Vila",
      "Fazenda",
      "Escola",
      "Hospital",
      "Delegacia",
      "Corpo de Bombeiros",
      "Banco",
      "Correios",
      "Supermercado",
      "Padaria",
      "Açougue",
      "Farmácia",
      "Restaurante",
      "Lanchonete",
      "Bar",
      "Cinema",
      "Teatro",
      "Museu",
      "Biblioteca",
      "Igreja",
      "Cemitério",
      "Parque",
      "Praça",
      "Zoológico",
      "Circo",
      "Parque de diversões",
      "Estádio",
      "Ginásio",
      "Piscina",
      "Academia",
      "Aeroporto",
      "Rodoviária",
      "Estação de trem",
      "Porto",
      "Navio",
      "Avião",
      "Ônibus",
      "Trem",
      "Metrô",
    ],
  },
};

function createPictionaryDB() {
  const db = {};
  Object.keys(PICTIONARY_DB_MASTER).forEach((id) => {
    const category = PICTIONARY_DB_MASTER[id];
    db[id] = {
      name: category.name,
      words: [...category.words],
    };
  });
  return db;
}
